# Generated by Django 3.2.6 on 2023-10-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='pefix',
            new_name='prefix',
        ),
    ]
