# Generated by Django 3.2.6 on 2023-11-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end',
            new_name='end_time',
        ),
    ]
