# Generated by Django 3.2.6 on 2023-11-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_end_schedule_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_time',
            new_name='start',
        ),
    ]
