# Generated by Django 3.2.6 on 2023-12-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_schedule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='color',
            field=models.CharField(default='#0071c5', max_length=7),
        ),
    ]
