# Generated by Django 3.2.6 on 2023-12-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_subjects_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='color',
        ),
    ]
